---
name: Release
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: github/ospo-reusable-workflows/.github/workflows/release.yaml@6a0a6d0de2227f9d5d11af90a87b2e2fd6b5463d
    with:
      publish: true
      release-config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  release_image:
    needs: release
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: github/ospo-reusable-workflows/.github/workflows/release-image.yaml@6a0a6d0de2227f9d5d11af90a87b2e2fd6b5463d
    with:
      image-name: ${{ github.repository_owner }}/issue_metrics
      full-tag: ${{ needs.release.outputs.full-tag }}
      short-tag: ${{ needs.release.outputs.short-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      image-registry: ghcr.io
      image-registry-username: ${{ github.actor }}
      image-registry-password: ${{ secrets.GITHUB_TOKEN }}
  release_discussion:
    needs: release
    permissions:
      contents: read
      discussions: write
    uses: github/ospo-reusable-workflows/.github/workflows/release-discussion.yaml@6a0a6d0de2227f9d5d11af90a87b2e2fd6b5463d
    with:
      full-tag: ${{ needs.release.outputs.full-tag }}
      body: ${{ needs.release.outputs.body }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      discussion-repository-id: ${{ secrets.RELEASE_DISCUSSION_REPOSITORY_ID }}
      discussion-category-id: ${{ secrets.RELEASE_DISCUSSION_CATEGORY_ID }}
